### ISSUE TITLE
Add configuration options.

### ISSUE THREAD

**Issue by kirillzhosul** [kirillzhosul/cookie-widget#3]

**Comment by DanilTezin** [comment]
How should it look and work?

**Comment by kirillzhosul** [comment]
> How should it look and work?

`widget.js` will allow to instantiate `CookieWidget` object, that will expect configuration options in constructor. As some services uses something like _Widget ID_, that requires backend server which is not allowed. Another possible way to solve this, GET HTTP parameters, which is also requires backend (there is no way to include script with GET parameters that is being changed by static proxy, actually this is done by injecting/templating inside script by the backend engine).

**Comment by kirillzhosul** [comment]
Or maybe there will be some server-hosted version (mono repository), this is optional and will load injected `widget.js` script.
I will look at this if method above will be weird or whatever else reason.

**Comment by DanilTezin** [comment]
I think the server version will be a great solution
